{
  "source_1": {
    "cdc_trigger": 50000,
    "file_format": "parquet",
    "format_id": "ERP_F1",
    "source_name": "maximo_type_1",
    "tables": [
      {
        "classification": "confidential",
        "entity_id": "ERP_F1_000",
        "landing_path": "s3://apa-ingestion-data/A_PM",
        "special_fields": [{field_id: pm_id, classification: APA-Protected, frequent_processing: Yes}],
        "table_name": "A_PM",
        "column_mapping": []
      },
      {
        "classification": "confidential",
        "entity_id": "ERP_F1_001",
        "landing_path": "s3://apa-ingestion-data/AMCREWLABOR",
        "special_fields": [{field_id: test_tfn, classification: APA-Protected, frequent_processing: No}],
        "table_name": "AMCREWLABOR_test",
        "column_mapping": []
      },
      {
        "classification": "confidential",
        "entity_id": "ERP_F1_002",
        "landing_path": "s3://apa-ingestion-data/COURSES_DETAILS",
        "special_fields": [{field_id: id, classification: APA-Protected, frequent_processing: Yes}],
        "table_name": "COURSES_DETAILS",
        "column_mapping": [{old_column_name: course_name , new_column_name: name}]
      }

    ],
    "tags": {
      "Business_Domain": "ERP",
      "ORG": "APA",
      "Source_System": "Maximo"
    },
    "time_zone": "Australia/Melbourne",
    "version": 1.0
  }
}